name: PR automatico para cada commit
on:
  push:
    branches:
      - develop
jobs:
productionPromotion:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
        with:
        ref: production
    - name: Reset branch
        run: |
        git fetch origin develop:develop
        git reset --hard develop
    - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
        branch: m0t4