name: PR automatico para cada commit
on:
  push:
    branches:
      - develop
jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Raise PR Mota
        id: mota
        uses: peter-evans/create-pull-request@v3
        with:
          branch: mota
          base: develop
          title: PR_
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_NAME }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_NAME }}">
          body: Criacao automatica de PR
          token: ${{ github.token }}
          delete-branch: false

      # - name: Raise PR Vinicius
      #   id: vinicius
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     branch: "vinicius"
      #     base: develop
      #     title: "PR de Vinicius"
      #     committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
      #     author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
      #     body: Criacao automatica de PR
      #     token: ${{ github.token }}
      #     delete-branch: false
